### PR TITLE
minor edits and WW revisions to section 3.3

### PR DESCRIPTION
**Pull request by Alex-Jordan**
This is a section my students are currently in, so it jumped in line.

### CODE REVIEW

**Comment by sean-fitzpatrick** [comment]
@Alex-Jordan do you have any work done on Chapters 4 and 5 that isn't yet on GitHub?
I've been working on typo corrections at the other end of the book to avoid merge conflicts with what you're doing. (I've done chapters 6 - 9 and I'm working on 10.)
But I could go right now to Chapters 4 and 5 and get those merged into master before you get there.

**Comment by Alex-Jordan** [comment]
I've only been in chapters 1, 2, and 3, since that is the "calculus I" that we teach here. At the very end, section 4.2.

So no conflicts in 4 and beyond. About to do 3.4, then maybe return to 1.4 where I left off. The chapter 1 and 2 stuff is there already, just not vetted against that spreadsheet I shared with you.

**Comment by sean-fitzpatrick** [comment]
OK. I've accessed the spreadsheet but haven't looked at it much. Trading between working and watching kids here, so I try to dive right into something when I can. (That or I spend all of my allotted time catching up on the emails that arrived while watching kids.) I'll look over Chapter 4 right now.

**Comment by Alex-Jordan** [comment]
Now with section 3.4 too.

No need for you to review/merge. I'll probably do that in another day or two. Just giving you the opportunity to look it over.

**Pull request merged**
