### PR TITLE
Small fixes to text without major changes

### PR DESCRIPTION
**Pull request by APEXCalculus**
Fixed small typo issues mostly.

Created a new image for a solution, so tikz code is updated.

Note: I'm unable to process .ptx files on my pc, so while I'm pretty sure these will compile correctly, I am unable to test them.

### CODE REVIEW

**Comment by sean-fitzpatrick** [comment]
These all look good to me. I'll wait on merging in case there's anything more to be added.

**Comment by sean-fitzpatrick** [comment]
I should add: if you want to process PreTeXt without installing anything on your PC, it's possible to do that now using GitHub Codespaces. (As an education user you can set this up for free.) Details on how to get set up are in the [PreTeXt guide](https://pretextbook.org/doc/guide/html/tutorial.html)

**Comment by sean-fitzpatrick** [comment]
@APEXCalculus let me know when you are done on this branch. All the changes so far are safe to merge.

I was busy with a workshop last week, but I'm hoping to catch up on all the activity on here this morning.

**Comment by APEXCalculus** [comment]
Go ahead and merge; we can likely then delete the branch afterwards.
I'm probably not using git best-practice, but I'm trying to keep the number
of commits per branch minimal.

**Pull request merged**
