### PR TITLE
Chapters 1, 2, and 3

### PR DESCRIPTION
**Pull request by sean-fitzpatrick**
I already did a reconciliation on Chapter 1, but didn't add in the videos (commented out, of course). To be consistent with other chapters, I did that now.

For Chapters 2 and 3: there were a few typos that were caught on the videos branch but not in master. Those are addressed.
For sections that @Alex-Jordan has not done recent WeBWorK work on, I removed the deprecated <setup> tag from WeBWorK problems.
(For the sections that Alex has worked on, changes went in the other direction -- I updated the webwork on the videos branch.)

The two branches should now be even except for videos, once the last two pull requests go through.
(But note that the previous PR has those changes on tangent planes that need review from @APEXCalculus .)

Once all this goes through, I might delete the videos branch here and have it live on my fork with a new name.
I plan to have a main branch that is kept even with this one, and two branches where I adjust the table of contents to match our two calculus streams.

### CODE REVIEW

**Comment by sean-fitzpatrick** [comment]
Caution: I'm not sure I did the right git thing on this branch, so don't merge it until after #80 (and possibly rebasing).
On my fork I wanted to be able to build the HTML to check changes. So I merged the changes from #80 (but only on my fork), and then later added this branch. So it has the changes from the previous pull request as well.

If this is bad I can withdraw this PR and wait for #80 to go through.

**Comment by Alex-Jordan** [comment]
I can't say for sure, but I have a lot of uncommitted work on chapters 1, 2, and 3. This may lead to a bunch of conflicts when I get back to combing out that work. 

I guess it's also hard to assess this PR because of having 31 commits over 50 files. And at a glance, a lot of the files are not from chapters 1, 2, or 3. How hard would it be for you to make more targeted pull requests?  And if possible, ones that don't touch on chapters 1, 2, 3?

**Comment by sean-fitzpatrick** [comment]
Most of the commits here were in the previous pull request that updated the last chapter and cleaned up some things in chapters other than 1, 2, 3. I'm going to close this. I'll see if a new PR is more focused.

**Comment by sean-fitzpatrick** [comment]
@Alex-Jordan doing a comparison now, a new PR from the same branch is 9 commits changing 17 files.
Most changes are of two types:
- removing periods from end of captions
- removing the deprecated `<setup>` tag from webwork problems.

Also: after doing a merge into master on my fork, I can now merge automatically from my fork into the `master` branch here.
That results in 101 files changing!!!! But there are again a few categories that cover the vast majority of changes:
1. In the master branch I got rid of some adjustments to the ordering of sections that I made to fit our local courses.
2. I resized videos in examples from 90% to 98%
3. I changed the size of Asymptote figures from 200x200 to 282x282 since that's the size we display them at.

**Comment by Alex-Jordan** [comment]
Hi @sean-fitzpatrick , I'm cool with whatever you are doing since I had to drop off the map with this project for a while. Give me one more week and I'll be in the APEX game. I think I saw a suggestion to get the branches sorted by the end of August, so I'll make it in time for that.

**Comment by sean-fitzpatrick** [comment]
Thanks @Alex-Jordan
On my fork all the branches are in good shape. And I can merge without conflict back to the master branch here.
Somewhere (an issue on here I think but maybe also the Google forum) I have a to-do list of small fixes. I can apply those before or after you commit your work.

But I wonder: where is best to commit your changes? Here, or on my fork (which is now a ways ahead).

I can merge without conflicts but then you'll have lots of conflicts to resolve.
Same is probably try if we do it in the other order, except then it's me who will have all the merge conflicts :-)

**Comment by Alex-Jordan** [comment]
Whatever works best for you is the right thing to do right now. It's on me for being behind, so I can deal with any conflicts.

**Pull request closed without merging**
