### PR TITLE
accumulated webwork corrections

### PR DESCRIPTION
**Pull request by Alex-Jordan**

### CODE REVIEW

**Comment by Alex-Jordan** [comment]
This also has a commit that sets things up for TikZ in webwork. 

You will need some things for this to work.

- Maybe the WW server still needs some configuration to get TikZ in WW working in general.
- mathbook needs https://github.com/rbeezer/mathbook/pull/1482 to be merged. If you are eager, you could grab that commit.
- You need to do `make pg-macros` which makes an `APEX.pl` file. Put this in the host course's `macros/` folder. It contains the `latex-image-preamble` stuff. You just need to make it once, unless `latex-image-preamble` changes.
- Actually that macro library should go someplace more central if you will assign the exercises to students in courses other than the host course. I think ideally, `APEX` gets a folder in the OPL macros folder and it goes there.

**Comment by rbeezer** [comment]
https://github.com/rbeezer/mathbook/pull/1482 is merged.

**Comment by sean-fitzpatrick** [comment]
Wow, I'm coming to this much later than intended! Summer session teaching is a pain.
Taking a look at this now. My WW server for APEX has been upgraded. (Not my production server -- that's on the to do list for this week -- this server has nothing but a course that serves as the backend for APEX.)

**Comment by sean-fitzpatrick** [comment]
> * You need to do `make pg-macros` which makes an `APEX.pl` file. Put this in the host course's `macros/` folder. It contains the `latex-image-preamble` stuff. You just need to make it once, unless `latex-image-preamble` changes.
> * Actually that macro library should go someplace more central if you will assign the exercises to students in courses other than the host course. I think ideally, `APEX` gets a folder in the OPL macros folder and it goes there.

Any reason (other than needing to add it to `.gitignore`) that I shouldn't put the file in `pg/macros/`?

**Comment by Alex-Jordan** [comment]
You could put it there. The git tracking is why I would consider
somewhere else. If you add it to .gitignore, then a diff will show up
on .gitignore. Personally I would put it somewhere in an OPL macros
folder to keep pg "clean". But yeah, you could put it there.

On Fri, Jun 25, 2021 at 9:44 AM Sean Fitzpatrick
***@***.***> wrote:
>
> You need to do make pg-macros which makes an APEX.pl file. Put this in the host course's macros/ folder. It contains the latex-image-preamble stuff. You just need to make it once, unless latex-image-preamble changes.
> Actually that macro library should go someplace more central if you will assign the exercises to students in courses other than the host course. I think ideally, APEX gets a folder in the OPL macros folder and it goes there.
>
> Any reason (other than needing to add it to .gitignore) that I shouldn't put the file in pg/macros/?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.



-- 
Alex Jordan
Mathematics Instructor
Portland Community College

**Comment by sean-fitzpatrick** [comment]
Instead of `.gitignore` I can just add the file to `.git/info/exclude` since that isn't tracked by default.

**Comment by sean-fitzpatrick** [comment]
Update: the APEX.pl file has to go in the course macros folder. Running the webwork extraction failed with it in pg/macros.

**Pull request merged**
