### PR TITLE
Clairfy closed interval terminology

### PR DESCRIPTION
**Pull request by sean-fitzpatrick**
Address Issue #165.

### CODE REVIEW

**Comment by sean-fitzpatrick** [comment]
@APEXCalculus please let me know if these changes are sufficient to address #165. If not, I can make additional changes as needed.

**Comment by sean-fitzpatrick** [comment]
Actually there is a related item brought up by @Alex-Jordan in #156. Should we clarify what is meant by a function being "continuous on its domain" when that domain is not connected?

We want to say something like, "If the domain is a union of intervals, a function is continuous on its domain if it is continuous on each interval." Except...

- The domain of the step function is all real numbers, but we can write this as a union of half-open intervals, on each of which the function is continuous
- A function like `\sqrt(x^2-1)` has domain `(-\infty, -1]\cup [1, \infty)`, which most students would consider to be a union of half-open intervals. (We do not want to start talking about the subspace topology...)

So if we wanted to formalize the definition of "continuous on its domain" we would need something that can distinguish between these two examples without getting into some sort of topological quagmire. (I guess the difference between the two is that the intervals in the first example cannot be separated by open sets, but how do you explain that in Calc 1?)

**Comment by sean-fitzpatrick** [comment]
Sorry, one last question: do we want to introduce the language "closed and bounded" for intervals of the form [a, b]?

I don't think "bounded" shows up in the single-variable material, but it's what we use for the Extreme Value Theorem in several variables.

**Comment by APEXCalculus** [comment]
Should the current pull request be merged, then another submitted to make a change similar to what I suggested? What's the standard way of adjusting a pull request?

**Comment by sean-fitzpatrick** [comment]
This one is my pull request, so the easiest way to adjust is for me to add a new commit, based on your suggestion. I'll do that now :-)

**Pull request merged**
