### PR TITLE
Convert ordered lists in exercises to tasks, where appropriate

### PR DESCRIPTION
**Pull request by sean-fitzpatrick**
Many exercises had parts that were marked up using ordered lists.
Current best practice is to structure these by `task`, instead.

This pull request does so. Turns out there were a **lot** of these, so this is a pretty big pull request.
I would appreciate it if someone has the time to review it, despite the size.

Note that I didn't deal with cases where the `ol` is in the introduction to an exercise group. In most of these cases, the exercise itself didn't have parts, although these are implied by the exercise group introduction. A `ol` still appears in the solution, if there is one.

(**NB**. Many of these 'solutions' are in fact just collections of answers. A later round of exercise revisions should probably address this.)

### CODE REVIEW

**Comment by sean-fitzpatrick** [comment]
The merge conflicts were unexpected. @Alex-Jordan if you can see a way for me to resolve them on my end, I'll try to so. But it seems to just not like some of the edits being made.

In any case this is not yet ready to merge: I still have to add labels (for Runestone) to all the tasks I created.
(All 549 of them...)

**Comment by Alex-Jordan** [comment]
The conflicts are from when you added `webwork-` to some xml:ids. Or rather, that you did not add them on the branch where you were doing task stuff. Maybe if you do that now on this branch, it will be fine. Looks like only 6 instances.

**Comment by sean-fitzpatrick** [comment]
Ah, right. I created this branch off of `main` but started work before the other pull request was merged.

I could just merge main into my branch, unless that creates too much clutter in the git history.

**Comment by Alex-Jordan** [comment]
That sounds like a good way to do it. also `git rebase main` could help. Then you will need to force push.

**Comment by sean-fitzpatrick** [comment]
I think I'll try merging first. Every time I think I've figured out exactly what rebase is going to do, I've been wrong...

**Comment by sean-fitzpatrick** [comment]
I've resolved the merge conflicts and I've added labels to all the tasks, for Runestone use.

I think this is good to go, pending testing and review. (I'll run a build tonight to see if I've inadvertently introduced any problems.)

**Comment by sean-fitzpatrick** [comment]
Caught of couple of mistakes while building. I think this is all set now, with the main issue being that someone else might have made different choices than I did in terms of what should be converted to use parts. I basically just searched for all occurrences of an `<ol>` within `<exercises>`. If it was within the `statement` of an exercise, I converted to tasks.

I didn't convert when there was the following structure:

```
<exercisegroup>
  <introduction>
    <p>Do all these things:
      <ol>...</ol>
    </p>
  </introduction>

  <exercise>
    <statement>
      <p>Do the things to this other thing</p>
    </statement>
    <solution>
      <p>
        <ol>...</ol>
      </p>
    </solution>
  </exercise>
```

**Comment by sean-fitzpatrick** [comment]
I am going to revisit some of the cases where the `<ol>` is in the introduction to the exercise group. In particular, to try to resolve the issue noted by @APEXCalculus in #245 .

**Comment by sean-fitzpatrick** [comment]
As discussed in #245, we can't resolve the issue there with tasks.

Does anyone have any objections to merging this? It's a big pull request, but I am working on another one right now, and I'm realizing that I'm going to run into merge conflicts: I'm working on converting more of the webwork-generated graphs into TikZ.

But some of those graphs are in exercises that I've also converted to use tasks.

Do we want to merge this now to avoid conflicts with the next PR?
Or leave this open for review and deal with any conflicts when they happen?

**Comment by APEXCalculus** [comment]
I think I'm fine with merging, but I can't test the pretext to ensure it does what we want. I have to trust Sean on that (which I'm fine doing). I just don't want to merge without acknowledging that.

**Comment by sean-fitzpatrick** [comment]
If you want to look over the HTML, I've built it with these changes:
https://opentext.uleth.ca/apex-calculus/

I can build the LaTeX but it takes so long to get all the figures in the right place.

**Comment by APEXCalculus** [comment]
You're working earlier in the morning than I expected!
I haven't examined every change, but I think it looks good, especially if it is compiling well enough for you. I'll merge.

**Comment by sean-fitzpatrick** [comment]
Ah yes. Funny story. I spent all of last week in Banff for a workshop at the Banff International Research Station.
The inevitable consequence of spending 5 days indoors with people who arrived by plane ensued, and now I am stuck in my basement in covid quarantine. I am feeling better but this morning's test was emphatically positive, so it's not yet time to rejoin the family.

In the basement I've got nothing better to do than work.

**Pull request merged**
