### PR TITLE
Fix errors in geometric series presentation

### PR DESCRIPTION
**Pull request by sean-fitzpatrick**
Attempt at fixing the errors noted in #173

### CODE REVIEW

**Comment by sean-fitzpatrick** [comment]
I've also included a fix to the typo noticed in #174

**Comment by sean-fitzpatrick** [comment]
I've also made a change to the definition of a bounded sequence, as suggested in #172

**Comment by APEXCalculus** [comment]
This seems ok to me. I didn't compile it to read properly & check for typos, etc.

If Alex has time to read, I can leave it for him to look at, too. Or I can Merge soon.

**Comment by sean-fitzpatrick** [comment]
I'm currently building a version of the book that has all the changes from the 4 pull requests I opened today. But I'm rebuilding all the assets, including webwork, which takes awhile. Once it's done I'll put it online for you to look at.

**Comment by sean-fitzpatrick** [comment]
@APEXCalculus New versions are up: [with video](https://opentext.uleth.ca/apex-video/) and [without video](https://opentext.uleth.ca/apex-calculus/)

You can take a look to see if things are better now.

**Comment by sean-fitzpatrick** [comment]
Note that you might have to do a `Ctrl-Shift-R` hard refresh to clear out any cached version.

**Comment by APEXCalculus** [comment]
@sean-fitzpatrick Thanks for the updated version online. Much easier to read.

Don't have time to make changes myself: part #2 of the geometric proof should have "if |r| > 1...", otherwise the comment about the sign of r doesn't make sense.

**Comment by sean-fitzpatrick** [comment]
@APEXCalculus I meant to remove that line -- I separated the `r>1` and `r<-1` cases, since the explanation is different in each case. I've just pushed an update to remove the line about the sign of r.

**Comment by sean-fitzpatrick** [comment]
I also made an edit to the `project.ptx` file. (It had to go somewhere and I didn't feel like opening a new pull request just for that.)

**Pull request merged**
