### PR TITLE
More miscellaneous edits

### PR DESCRIPTION
**Pull request by sean-fitzpatrick**
This pull request takes care of a few more outstanding issues.

I am going to take a moment to see if I can do anything about #179 and then call it a week.

### CODE REVIEW

**Comment by sean-fitzpatrick** [comment]
I've added a commit that attempts to adjust the language related to power series, as discussed in #179 .

I'm fairly certain that both @APEXCalculus and @Alex-Jordan will want to suggest edits to what I've proposed.

**Comment by sean-fitzpatrick** [comment]
I made some adjustments. I didn't add the last sentence ("The following theorem...") since we have replaced the theorem with a Key Idea.

**Comment by APEXCalculus** [comment]
I think all this looks good. I can merge, but I will wait in case someone else wants to look it over first.

**Comment by sean-fitzpatrick** [comment]
Since #179 was opened by @Alex-Jordan I'll wait to see if he's happy with the change here.

**Comment by Alex-Jordan** [comment]
I think you should do what you and @APEXCalculus think best. Circumstances here are such that I'm not teaching calculus these days and I don't expect to for a while. And most (not all) of my colleagues are choosing to us either Stewart or OpenStax. So I think my role with APEX evolution can be more of a technical advising role now about WeBWorK and PreTeXt, and maybe you can tolerate my musings and observations every now and then like #179. But you two should steer things.

FWIW, I did read over the ratio test/ interval of convergence edits and I think it's good.

**Comment by sean-fitzpatrick** [comment]
I still really want to know what it is that people are in OpenStax that I don't. Any time I've looked at their stuff, it seemed to me that whatever money they're making is not being reinvested in improving the books...

In any case, I'll go ahead and merge this.

When I'm at my computer (currently on phone) I'm going to post here with a WeBWorK problem that has me stumped.
Somewhat at random it will fail to build, always the same problem. But every time I re-run with debugging turned on, it builds without any problem.

**Pull request merged**
