### PR TITLE
undo merge

### PR DESCRIPTION
**Pull request by Alex-Jordan**
@sean-fitzpatrick Does this do what you'd like? I'm not 100% following what happened. Here I just pulled main, then `git reset HEAD~1` to undo the most recent commit which was a merge commit. Then I cleared all the changes and committed as "undo merge".

### CODE REVIEW

**Comment by sean-fitzpatrick** [comment]
@Alex-Jordan I don't think it reverts things back to how they were, but this might be OK.

E.g. if I look at the files that were changed, I see things like this:
image

But maybe this is OK?

That is, I think your pull request here is effectively the pull request that I wanted to make: it contains all of the changes that I was trying to stage for a pull request, but not the last merge commit.

So now there is something that can be reviewed to make sure everyone else is happy with the changes.

I don't think it lets us undo those changes, but at least it makes it easier to look things over to make sure everything is OK.

**Comment by sean-fitzpatrick** [comment]
I think what happened is I was trying to pull a change from here onto my fork, and somehow trying to resolve a conflict between the two `project.ptx` files resulted in GitHub deciding to sync in both directions?

Anyway `main` now has a whole pile of commits that are from the students I had working for me last term.

I'll review and try to provide a summary of any changes that are not image descriptions.

**Comment by sean-fitzpatrick** [comment]
I've gone over all the changes.

99% of changes are the addition of description and short description to images.
Other changes:
- minor adjustments to a small number of TikZ images that we noticed didn't look right while writing the desciptions
- in a couple of sidebyside figures, we wrapped the images in a figure with an empty caption, so that we could xref the figure in the description
- small changes in `apex.ptx` and `docinfo.ptx` to address some deprecations introduced in last few months by Rob.

The number line figures in Chapter 3 still need a bit of work. That will come in a separate pull request.

I had a team of 7 students working on descriptions, so there will be some variation in writing style, but I think having imperfect (but adequete) descriptions is better than having no descriptions.

**Comment by sean-fitzpatrick** [comment]
@APEXCalculus this will add image descriptions in the HTML for about 60% of the book. Any reason not to merge?

**Comment by APEXCalculus** [comment]
I have no problem with it, for sure. I should have merged earlier; was just making sure all the mistakes were successfully undone.

**Pull request merged**
