### PR TITLE
Pubfile update

### PR DESCRIPTION
**Pull request by sean-fitzpatrick**
I think this should update our publication, project and style files with regard to the recent work to migrate most remaining string parameters to the publication file.

### CODE REVIEW

**Comment by Alex-Jordan** [comment]
If this is working for you, I say go for it and merge it. I'm not in a position where I could test things right now.  I skimmed it and didn't see anything to wonder about.

**Comment by sean-fitzpatrick** [comment]
Assuming there are no mistakes in the new documentation, this should be fine. I haven't done a LaTeX build yet, however. I'll do that this afternoon. (Keeping in mind that this will not include the follow-up work to make all the changes, like margin figure placement, that we're not able to encode in our source somehow.)

**Comment by sean-fitzpatrick** [comment]
I've added a line to the publication files for HTML that enables the "CRC" layout (centred, with round corners).

If you'd like to see what this looks like, I've just put a [copy up on the web](https://opentext.uleth.ca/apex-crc).
It's possible not everyone will prefer this layout, but having it in the publication file seems better than not: anyone who doesn't like it can just comment out that line.

**Comment by sean-fitzpatrick** [comment]
I'm going to merge this, which will make CRC the default

**Pull request merged**
